FROM ruby:3.3-bookworm

ARG UID=1000
ARG GID=1000

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    libpq-dev \
    libxml2-dev \
    libxslt1-dev \
    pkg-config \
    nodejs \
    tini \
  && rm -rf /var/lib/apt/lists/*

RUN groupadd -g ${GID} scalelite \
  && useradd -m -u ${UID} -g ${GID} -s /bin/bash scalelite

WORKDIR /srv/scalelite

RUN gem install bundler -v 2.5.22

ENV BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    BUNDLE_PATH=/usr/local/bundle

USER scalelite

EXPOSE 3000
